const coreTeamMembers = [
  {
    name: "Rakshitha C",
    role: "App Content Writer",
    image: "https://drive.google.com/uc?id=1iLJh49oTg1MsUcofaor9ZJXsSlo9NpYO",
    linkedin: "https://www.linkedin.com/in/",
    twitter: "https://x.com/",
    instagram: "https://www.instagram.com/",
  },
  {
    name: "Anjali Kushwaha",
    role: "Graphic Design",
    image: "https://drive.google.com/uc?id=1oHpbtpdmk0giCdZWRWwHriWmHhEugj1R",
    linkedin: "https://www.linkedin.com/in/",
    twitter: "https://x.com/",
    instagram: "https://www.instagram.com/",
  },
  {
    name: "Harsha Nandi",
    role: "Program manager",
    image: "https://drive.google.com/uc?id=1VUc-Mendd1zDtqOEgtkAAY6DlfgqOG-N",
    linkedin: "https://www.linkedin.com/in/",
    twitter: "https://x.com/",
    instagram: "https://www.instagram.com/",
  },
  {
    name: "Jyoti Singh",
    role: "Content Writing",
    image: "https://drive.google.com/uc?id=1RZSUIZSlfzwMlgLxMnQwamfYzvpV39To",
    linkedin: "https://www.linkedin.com/in/",
    twitter: "https://x.com/",
    instagram: "https://www.instagram.com/",
  },
  {
    name: "Shubhanshu Kumar",
    role: "Web Developer",
    image: "",
    linkedin: "https://www.linkedin.com/in/",
    twitter: "https://x.com/",
    instagram: "https://www.instagram.com/",
  },
  {
    name: "Varshitha Narra",
    role: "PR & Sponsorship",
    image: "https://drive.google.com/uc?id=1OtdaqN0mxAz1QQYkvUjRm1Jbeip0Io8R",
    linkedin: "https://www.linkedin.com/in/",
    twitter: "https://x.com/",
    instagram: "https://www.instagram.com/",
  },
  {
    name: "Kajal Biju",
    role: "PR & Sponsorship",
    image: "https://drive.google.com/uc?id=1H5F86uWxPNSL7NIqiCOQwHU8TcHHeg4M",
    linkedin: "https://www.linkedin.com/in/",
    twitter: "https://x.com/",
    instagram: "https://www.instagram.com/",
  },
  {
    name: "Karan Sewmal",
    role: "Web Developer",
    image: "https://drive.google.com/uc?id=17xJnI_eCENrXOtiW18LdE9cnXhJha7uG",
    linkedin: "https://www.linkedin.com/in/",
    twitter: "https://x.com/",
    instagram: "https://www.instagram.com/",
  },
  {
    name: "Varun Sai",
    role: "Community Moderator",
    image: "https://drive.google.com/uc?id=1IMNSHX9L6YXTewKVEHjiWJgZrkvTg61m",
    linkedin: "https://www.linkedin.com/in/",
    twitter: "https://x.com/",
    instagram: "https://www.instagram.com/",
  },
];

export default coreTeamMembers;
